name: saltstack-git-formula
source: https://github.com/bechtoldt/saltstack-git-formula
summary: SaltStack Formula to set up and configure Git, a distributed revision control system
todo:
  - add instructions how to use formhelper, add information about it in the formula-docs (dependency), show up alternative?
  - 'table/ matrix: os/salt compatibility (dedicated file)'
  - add list of available states
  - add tests
